### PR TITLE
feat(radarr): NEW German guide

### PR DESCRIPTION
**Pull request by Lokilicious**
# Pull Request

## Purpose

Initial draft of the new german guide

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

## Todos

- [x] Include the need to merge qualities
- [x] 1080p x265 ban vs. vector and zerotwo releasing good quality x265
- [x] Change pictures of merged qualities
- [x] Change scores of resolutions
- [x] Add CFs for source (Bluray, Web)
- [x] Add note for releases where german is the original language where "German" and "German.DL" CF matches 
- [x] Rethink if we need 3 P2P Tiers
- [x] Add LD/MD CF to unwanted section
- [x] Find out which groups do which qualities
- [x] Split up Tier CFs by Quality
- [x] Adapt Tier CFs to include Quality Conditions
- [x] Create 1080p and 2160p german booster CF with conditions for resolution and language
- [x] Adapt scoring to final

### CODE REVIEW

**Comment by PCJones** [comment]
Should we add a note/link to the #linemic-dubbed LD/MD CF in the German Audio section?

**Comment by Lokilicious** [comment]
> Should we add a note/link to the #linemic-dubbed LD/MD CF in the German Audio section or move it to the German Audio section?
> 
> (haven't read through the whole thing yet, will do that in ~ 1 week)

Yes we should add it to the "Unwanted" section 👍

**Comment by hexoverflow** [comment]
Is there an update when this will be merged?

**Comment by m4tz3** [comment]
I have the same question.

**Comment by TRaSH-** [comment]
> Is there an update on when this will be merged?

When it's ready and there is no real ATA, something was mentioned in the Discord channel about when it will be expected, but it has been postponed several times already, and as you can see in the OP, a lot still needs to be done.
Questions like this and updates might have been faster on our Discord.

**Review by TRaSH- — APPROVED** [review]
Finished the last check and all the needed changes.

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
