### PR TITLE
fix(radarr): Add VOSTFR Anime Score

### PR DESCRIPTION
**Pull request by yammes08**
- Add a score to the french-vostfr json for `anime-radarr` for score sets compatibility
- Amend the anime Radarr includes file to use the json score

# Pull Request

## Purpose

The French VOSTFR custom format is used in the Radarr anime guide, but does not have an associated score, nor a default.

## Approach

- Add an `anime-radarr` score object to the French VOSTFR json
- Amend the Radarr anime guide to use the new score instead of a hard-coded figure

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by FonduemangVI — APPROVED** [review]
Looks good to me

**Review by nuxencs — APPROVED** [review]

**Comment by nuxencs** [comment]
I was a second too slow haha

**Comment by nuxencs** [comment]
just saw, isn't this PR a dupe of this? https://github.com/TRaSH-Guides/Guides/pull/1520

**Comment by yammes08** [comment]
Haha, I even did some work on the other one 😄 yeah, let's reject/close this one. Sorry folks.

**Pull request closed without merging**
