### PR TITLE
Update NZBGet page

### PR DESCRIPTION
**Pull request by dalton-morrison**
# Pull Request

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
If you want this merged, you will need to update the PR info and provide all the needed info
 
image

And your PR has a lint error that needs fixing

**Comment by zakkarry** [comment]
Fixed lint for you, since it's been a week since you PR'd this.

You still need to address the PR description as @TRaSH- mentioned if you want this to be merged.

**Comment by zakkarry** [comment]
dead PR?

**Comment by dalton-morrison** [comment]
I was trying to do this quickly but failed to follow through for a handful of reasons.  I will close this as a failed pull request to help eliminate dangling PRs.  I apologize for the hassle.

**Pull request closed without merging**
