### PR TITLE
feat(starr): Additions to Scene CF

### PR DESCRIPTION
**Pull request by zakkarry**
# Pull request

**Purpose**
Added multiple groups, both new and old, to the "Scene" CF

**Approach**
Referenced trackers and releases.

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ X ] Use github checklists. When solved, check the box and explain the answer.

**Requirements**
Check all boxes as they are completed

- [ X ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ X ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by nuxencs — CHANGES_REQUESTED** [review]
missing the necessary changes for the Sonarr v3 guide

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
also can you squash this down - [details](https://gist.github.com/lpranam/4ae996b0a4bc37448dc80356efbca7fa)

**Comment by zakkarry** [comment]
updated v3 sonarr to reflect changes, and squashed the commits down.

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
need to update the docs as well as mentioned
https://github.com/TRaSH-Guides/Guides/blob/master/docs/Sonarr/Sonarr-Release-Profile-RegEx.md

**Review by nuxencs — APPROVED** [review]

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
