### PR TITLE
chore(guides): fix several broken/forgotten anchors

### PR DESCRIPTION
**Pull request by TRaSH-**
# Pull Request

## Purpose

fix several broken/forgotten ~~links~~ anchors

## Approach

Noticed that some ~~links~~ anchors where broken/forgotten so fixed them.

## Open Questions and Pre-Merge TODOs

- [x] Tested Locally

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by zakkarry** [comment]
How did this build with broken links?

**Review by zakkarry — APPROVED** [review]

**Comment by TRaSH-** [comment]
> How did this build with broken links?

image

I don't know, but i noticed these errors and i was curious what the cause was

**Comment by zakkarry** [comment]
I dont think anchors count as broken links, were _ALL_ the errors anchors? because technically speaking an anchor still links to a valid page, so that might be why....

**Comment by TRaSH-** [comment]
well updated the PR title and the description.

**Pull request merged**
