### PR TITLE
feat(starr): Add upscaled to Sonarr and add UPS

### PR DESCRIPTION
**Pull request by TRaSH-**
# Pull Request

## Purpose

- Add NEW CF Upscaled to Sonarr
- Add UPS to CF Upscaled
- Fix: #1732 

## Approach

- [x] Added NEW CF Upscaled to Sonarr
- [x] Added UPS to CF Upscaled
- [x] Updated Regex test case

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
@nuxencs can you check if you can improve this CF ?

**Review by yammes08 — DISMISSED** [review]
Nice one, looking good!

**Comment by nuxencs** [comment]
> @nuxencs can you check if you can improve this CF ?

could be improved to this one, but might need to check for false positives
https://regex101.com/r/KWCP1y/1

**Comment by TRaSH-** [comment]
> > @nuxencs can you check if you can improve this CF ?
> 
> could be improved to this one, but might need to check for false positives https://regex101.com/r/KWCP1y/1

then we need to hold it for now, till someone can do some testing

**Comment by yammes08** [comment]
Set as draft pending testing (so it doesn't get merged)

**Comment by TRaSH-** [comment]
perhaps we should just use the regex i made, and review/test the new one when we have some spare time. otherwise this one will stay open for a long time

**Comment by yammes08** [comment]
Actually, this will need adding to the collections pages and the unwanted part of the guides pages. I'll push some commits.

**Pull request merged**
