### PR TITLE
feat(starr): Add SobsPlease

### PR DESCRIPTION
**Pull request by sdaqo**
# Pull Request

## Purpose
Adds SobsPlease group to web fantranslation. They do fantranslations and are currently the only group that makes proper Girls Band Cry subs (there are no official ones) 

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by nuxencs** [comment]
this looks like a one off group to me tbh, but for the anime group to decide 😄

**Comment by sdaqo** [comment]
Yeah you are right, they are called sobs please after all, but I thought it wouldn't hurt and maybe they do continue.

**Comment by rg9400** [comment]
I think we can maybe add them because this isn't the first request for this group.

**Review by rg9400 — APPROVED** [review]

**Comment by TRaSH-** [comment]
Because of the merge freeze we have it won't be merged before the start of the weekend.

**Pull request merged**
