### PR TITLE
feat(guides): Move AV1 to unwanted

### PR DESCRIPTION
**Pull request by yammes08**
# Pull Request

## Purpose

Resolve: #1962 

## Approach

- [x] Remove AV1 from Radarr and Sonarr optional guide sections.
- [x] Add AV1 to Radarr and Sonarr unwanted guide sections.
- [x] Add AV1 to Radarr and Sonarr profile JSON files.
- [x] Built and tested locally.

## Open Questions and Pre-Merge TODOs

None

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by yammes08** [comment]
> @yammes08 your pull request title "Feat(guides): Move AV1 to unwanted" does not conform to our [naming conventions](https://www.conventionalcommits.org/en/v1.0.0/).
> 
> Please update the title to match the pattern: "feat|build|chore|style|fix|update|ci(<area>): <description>
> 
> You can check your title at this [regex101 link](https://regex101.com/r/jOZ6kU/1)."

Updated

**Comment by yammes08** [comment]
I also added `.DS_Store` to `.gitignore`.

**Review by TRaSH- — APPROVED** [review]
Tested it locally on the different quality profiles and i didn't see any issues

**Comment by yammes08** [comment]
> Tested it locally on the different quality profiles and i didn't see any issues

I need to update the Collection tables before merging.

**Review by mvanbaak — APPROVED** [review]
LGTM

**Review by TRaSH- — APPROVED** [review]
approved after a minor change

**Pull request merged**
