### PR TITLE
fix(starr): Moved webdl and webrip into Amazon regex to prevent incorrect matches

### PR DESCRIPTION
**Pull request by wheat4714**
# Pull Request

## Purpose

I created this pull request because I noticed that Amazon CF was applying to certain TV shows and TV episodes. I noticed that the regex is simply looking for "Amazon" in a word boundary. As this is a dictionary word, it's going to match stuff it shouldn't.

## Approach

Instead of matching just "Amazon", it requires additional text either side of, which always comes with these releases. Either the resolution or web-rip / web-dl.

https://regex101.com/r/IR8Qbx/6

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by wheat4714** [comment]
@TRaSH- Better now https://regex101.com/r/IR8Qbx/8

I added a negative lookbehind for "the.amazon" as that seems to be a common pattern, but no sane person would label a streaming service "the streaming service".

I've left all the resolutions in the regex. Removing them would have fixed the incorrect matches as well. Whilst I was not able to find any releases where the resolution is present and WEB-DL/Web-Rip is not, I have only been scrolling through prowlarr results, so cannot be certain that there are none.

**Comment by nuxencs** [comment]
@wheat4714 this is a way simpler version and it still catches 90% of those cases. the last 10% are just horribly named releases.

https://regex101.com/r/kBRsQW/1

**Comment by nuxencs** [comment]
please make the same adjustment for the radarr cf

**Review by nuxencs — CHANGES_REQUESTED** [review]
please make the same adjustment for the radarr cf

**Review by nuxencs — CHANGES_REQUESTED** [review]
please also add back the removed `WEBDL` and `WEBRIP` conditions

**Review by nuxencs — APPROVED** [review]

**Comment by bakerboy448** [comment]
Reverting this. Breaking change that materially breaks sonarr rename functionality for existing episodes.

This was not actually tested in sonarr and only has blind regex performed

**Pull request merged**
