### PR TITLE
chore(sonarr): add 720p CF

### PR DESCRIPTION
**Pull request by dctr**
# Pull Request

## Purpose

Adding a 720p CF to sonarr.

## Approach

This is following the 2160p and 1080p formats already available for Sonarr, plus the 2160p, 1080p and 720p formats for Radarr, to complete the set.

Hash created via https://md5.gromweb.com/?string=Sonarr+720p

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
Just curious why would we want a CF for this resolution? 
Basically it wouldn't be needed being quality trump's all. 
The only reason Radarr has it, is because of a special quality profile where it's needed for the 1080p and 2160p

**Comment by dctr** [comment]
Yes, I am doing something similar than SQP for my TV shows, in that I combine certain qualities into a single profile and want to use resolution as one of the factors by which I rank what release I want. I can of course add this manually, but having it as a TRaSH rule would make my usage of recyclarr much more consistent.

I thought this addition wouldn't be too controversial, given that sonarr already has the 1080p and 2160p rules. But if you feel it goes against the principles of your guides, of course feel free to close/reject this.

**Comment by TRaSH-** [comment]
Seems we're also missing the 2160p in Sonarr, add that one also and i will accept it ;)

**Comment by dctr** [comment]
Will do, give me a few days, this week is pretty busy.

**Comment by TRaSH-** [comment]
> Will do, give me a few days, this week is pretty busy.

just  a ping so you don't forget

**Comment by dctr** [comment]
@TRaSH- , there is already a 2160p file, no? 😅 

https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/sonarr/cf/2160p.json

**Comment by yammes08** [comment]
Think this 720p CF also needs to be added to the Sonarr Collection of Custom Formats guide page.

**Comment by TRaSH-** [comment]
> Think this 720p CF also needs to be added to the Sonarr Collection of Custom Formats guide page.

we don't have the resolutions CF in the table, iirc not even in Radarr

**Review by TRaSH- — APPROVED** [review]

**Pull request merged**
