### PR TITLE
fix(starr): naming scheme for Emby

### LINKED ISSUE #1371: [Bug] Renaming format for emby: Changed - to =
**Which Guide**
Renaming format for emby

**Describe the Error in the Guide**
the current naming format for emby isnt great as emby now uses tvdib={id}, imdbid={id} and tmdbid={id} to identify shows with the dbid in the name the current format says to name them with tvdbid-{id} which is the old formatting.

**Additional context**
i had some issues with emby misidentifying tvshows when i followed the naming convention in the guides and i asked on the emby forums for help, where it was pointed out that emby isnt recognising the dbids in the names as they arent labeled in a way that emby recognises them and i was told the correct way to label them, i have since been testing this change to the naming format for a couple monts now and ive had no further issues with it mis-identifying shows or episodes

TV
Standard episode format
{Episode CleanTitle} - S{season:00}E{episode:00} - [tvdbid={TvdbId}] [imdbid={ImdbId}] - [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

Anime Episode Format
{Episode CleanTitle} S{season:00}E{episode:00} - {absolute:000} - [tvdbid={TvdbId}] [imdbid={ImdbId}] - [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRange]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

Series Folder Format
{Series CleanTitle} ({Series Year}) [tvdbid={TvdbId}] [imdbid={ImdbId}]

Movies
Standard Movie Format
{Movie CleanTitle} {(Release Year)} [imdbid={ImdbId}] [tmdbid={TmdbId}]- {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]{MediaInfo AudioLanguages}[{MediaInfo VideoBitDepth}bit][{Mediainfo VideoCodec}]{-Release Group}

Movie Folder Format
{Movie CleanTitle} ({Release Year}) [imdbid={ImdbId}] [tmdbid={TmdbId}]

https://emby.media/community/index.php?/topic/118056-incorrect-identity-tv-shows/

https://emby.media/support/articles/Movie-Naming.html

### PR DESCRIPTION
**Pull request by TRaSH-**
# Pull request

**Purpose**
Fix #1371

**Approach**
Separate Emby from Jellyfin from the naming scheme for both Sonarr and Radarr. Changed `-` to `=`

**Requirements**
Check all boxes as they are completed
- [x] check Radarr in local test setup
- [x] check Sonarr in local test setup
- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bakerboy448** [comment]
HOLD on merging - pending https://github.com/Radarr/Radarr/pull/8730

TBD on the required naming format for [] to be optional.

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
review to block the merge.

given `{Movie Title} [imdb={ImdbId}]`

results in `Movie Title ]`

**Comment by TRaSH-** [comment]
> review to block the merge.
> 
> given `{Movie Title} [imdb={ImdbId}]`
> 
> results in `Movie Title ]`

image

USED: `{Movie CleanTitle} ({Release Year}) [imdbid={ImdbId}]`
Result: `The Movie Title (2010) [imdbid=tt0066921]`

**Comment by bakerboy448** [comment]
[awaiting Q's advisement
](https://github.com/Radarr/Radarr/pull/8730#issuecomment-1604909935)
regardless - likely don't want this merged for radarr until radarr nightly supports it being conditional to prevent `[imdbid=]`

**Comment by TRaSH-** [comment]
ahh you mean when there is no known ID yet ?
then we wait as you suggested

**Comment by bakerboy448** [comment]
waiting on Radarr PR
image
https://github.com/TRaSH-Guides/Guides/pull/1386#issuecomment-1604819341

**Comment by bakerboy448** [comment]
Still waiting on radarr to support and likely someone from the community to develop that given the very limited dev time

**Comment by bakerboy448** [comment]
Likely a non-issue now. Emby has had support for plex style tags? https://github.com/Radarr/Radarr/pull/8730#issuecomment-1740335999

**Comment by nodiaque** [comment]
Emby support the - tag, from multiple years ago.

https://emby.media/support/articles/Movie-Naming.html
https://emby.media/support/articles/TV-Naming.html

= is one way of doing it but it support - no problem. In fact I have - everywhere since it started supporting it multiple years ago

**Comment by TRaSH-** [comment]
being that Emby now supports the standard what plex also uses, this can be closed

**Pull request closed without merging**
