### PR TITLE
style(guide): Update dv-hdr10plus.json to have consistent naming

### PR DESCRIPTION
**Pull request by AN1MATEK**
# Pull Request

## Purpose

The "HDR10+" and "HDR10+ Boost" both use the symbol "+" instead of the word "Plus" in the naming. I simply updated this file to be consistent.

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by zakkarry** [comment]
Maybe this too...

https://github.com/TRaSH-Guides/Guides/blob/master/docs/Sonarr/sonarr-collection-of-custom-formats.md?plain=1#L35

**Comment by AN1MATEK** [comment]
`Plus` is used in the guide as Title. `+` was always found in the arrs. I did not intend to correct the syntax in the guides, but the 2nd link you posted is in fact the json definition where I think the correction belongs.

It could be updated in the guide too, but that's another decision.

**Comment by nuxencs** [comment]
the arrs use `Plus` tho

**Comment by TRaSH-** [comment]
image
ahh you mean this in the guide, yeah good point

**Comment by AN1MATEK** [comment]
This is what I meant with the arrs

image

**Review by TRaSH- — APPROVED** [review]
Added the changes also in the collection table

**Pull request merged**
