### PR TITLE
feat(guide): Update quality size FAQ and preferred info

### PR DESCRIPTION
**Pull request by TRaSH-**
# Pull Request

## Purpose

Updated quality size FAQ and preferred info

## Approach

Updated quality size FAQ and preferred info, switched to tabbed option for standard and anime/animated/cartoons

## Open Questions and Pre-Merge TODOs

- [x] Update Radarr quality size FAQ and preferred info
- [x] Update Sonarr quality size FAQ and preferred info
- [x] Added animated/cartoons to the anime quality size
- [x] Switched to single includes file location to prevent multiple places to edit the same info
- [x] Added max preferred score to the table for  Sonarr/Radarr
- [x] Changed preference score in `anime.json` and `series.json`  to accurately reflect the scoring you receive in Sonarr.

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by TRaSH-** [comment]
#1831 I still don't understand why we should add this to the guide ?
shouldn't the info added be enough ?

image

**Comment by TRaSH-** [comment]
@bakerboy448 

image

would this cover issue #1831

**Comment by bakerboy448** [comment]
I think we should include the preferred score in the table as the words will be skimmed over

**Comment by TRaSH-** [comment]
image

added this to it, because if i set it to 399 we will get people complaining they can't set it to 399 and it reverts to 395.

**Review by zakkarry — APPROVED** [review]

**Pull request merged**
