### PR TITLE
chore(guide): Update mkdocs.yml w/ copyright year

### PR DESCRIPTION
**Pull request by BernCarney**
Just updating copyright year to be current year

# Pull Request

## Purpose

Quick change to update copyright year to be accurate.

## Approach

Updated copyright value in mkdocs.yml which should cascade down.

## Requirements

- [x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bakerboy448** [comment]
please update the PR title per [contribution guidelines](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md#pull-request-naming)

**Comment by TRaSH-** [comment]
Thx I'll take a look at it when I wake up

**Comment by owine** [comment]
Maybe the JS of `<script>document.write(new Date().getFullYear())</script>` would be better than the hardcoded date?

https://stackoverflow.com/questions/67983304/how-to-use-build-date-utc-for-copyright-year-in-mkdocs-yml

Dev also suggests using a mkdocs hook: https://github.com/squidfunk/mkdocs-material/discussions/4969#discussioncomment-7290363

**Comment by BernCarney** [comment]
> Maybe the JS of `<script>document.write(new Date().getFullYear())</script>` would be better than the hardcoded date?
> 
> https://stackoverflow.com/questions/67983304/how-to-use-build-date-utc-for-copyright-year-in-mkdocs-yml
> 
> Dev also suggests using a mkdocs hook: [squidfunk/mkdocs-material#4969 (reply in thread)](https://github.com/squidfunk/mkdocs-material/discussions/4969#discussioncomment-7290363)

This could work but you would want a fallback anyways in case the user has javascript disabled. Copyright is one of those weird circumstances where I lean towards hard-coded and have some checks in a linter or pre-commit hook to make sure it matches the current year vs relying on something dynamic.

**Pull request merged**
